Update MediaManager.php
sonata-project/SonataMediaBundle pull request #1871
Opened 2020-11-26 12:12 UTC by mrcmorales

## Subject

I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Added
- Added some `Class::newMethod()` to do great stuff.

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

2021-02-16 20:37 UTC, wbloszyk approved these changes

2021-02-16 23:37 UTC, phansys requested changes
Good job @mrcmorales!
Could you please add a test in order to avoid regressions?

2021-06-06 09:17 UTC, VincentLanglet commented
> Good job @mrcmorales!
> Could you please add a test in order to avoid regressions?

Can we still merge this @phansys ? It would be nice to avoid blocking a bugfix like this.

2021-06-06 10:23 UTC, core23 approved these changes

2021-06-06 10:23 UTC, core23 commented
> Could you please add a test in order to avoid regressions?

Do we need tests that a class contains some interface? oO

2021-06-06 10:32 UTC, phansys approved these changes
> Can we still merge this @phansys ? It would be nice to avoid blocking a bugfix like this.

Sure, we could add some tests later.

>Do we need tests that a class contains some interface? oO

If this is considered as bugfix, I think so. A call to `assertInstanceOf()` should be enough IMO.

2021-06-06 10:37 UTC, merged

2021-06-06 11:03 UTC, core23 commented
> If this is considered as bugfix, I think so. A call to `assertInstanceOf()` should be enough IMO.

A test should cover behavior not the design of a class.