Deprecate calling getContext without existing context
sonata-project/SonataMediaBundle pull request #2021
Opened 2021-08-08 14:12 UTC by jordisala1991

## Subject

I am targeting this branch, because this is BC.

Closes #2014 .

## Changelog

```markdown
### Deprecated
- Deprecate `getContext()` from Pool without first having that context.
```

2021-08-08 14:12 UTC, VincentLanglet submitted a review, later dismissed

2021-08-10 09:36 UTC, phansys requested changes

2021-08-10 09:36 UTC, phansys commented on src/Provider/Pool.php
> +                .'and will not be supported in version 4.0.',
```suggestion
                .' and will not be supported in version 4.0.',
```

2021-08-10 12:19 UTC, VincentLanglet approved these changes

2021-08-10 14:36 UTC, phansys approved these changes

2021-08-10 16:28 UTC, merged