Remove unused files
sonata-project/SonataMediaBundle pull request #2079
Opened 2021-08-18 07:26 UTC by jordisala1991

## Subject

I am targeting this branch, because on 3.x it could be considered a BC break

Closes #2073 .

## Changelog

```markdown
### Removed
- Removed unused doctrine skeleton files for SonataEasyExtends usage.
- Removed unused SonataAdminBundle translation files
- Removed unused jQuery Nivo Gallery dependency
```

2021-08-18 08:52 UTC, VincentLanglet reviewed
Are you sure about the translations ?

2021-08-18 09:29 UTC, jordisala1991 commented
I tried on sandbox. it is using SonataMediaBundle domain

2021-08-18 09:54 UTC, VincentLanglet commented
Was added here: https://github.com/sonata-project/SonataMediaBundle/pull/1627
Don't know if something was fixed to correctly use the label_catalogue

2021-08-18 09:54 UTC, VincentLanglet approved these changes

2021-08-18 13:17 UTC, jordisala1991 commented
Not at all, not sure what error was fixed, since there is no issue linked, but it works without this files.

2021-08-21 13:21 UTC, phansys reviewed
Could you please provide other PR for the 3.x branch adding a `NEXT_MAJOR` comment for these removals?

2021-08-23 06:20 UTC, jordisala1991 commented
> Could you please provide other PR for the 3.x branch adding a `NEXT_MAJOR` comment for these removals?

Dont know what you mean. Mind to explain?

2021-08-23 07:03 UTC, VincentLanglet commented
> > Could you please provide other PR for the 3.x branch adding a `NEXT_MAJOR` comment for these removals?
> 
> Dont know what you mean. Mind to explain?

Adding a "Next major remove this file" message in those files in a 3.x PR I think

2021-08-23 07:57 UTC, core23 requested changes

2021-08-23 07:57 UTC, core23 commented on src/Resources/translations/SonataAdminBundle.de.xliff
> -<?xml version="1.0" encoding="UTF-8"?>
This files should be kept. They are needed for this: https://github.com/sonata-project/SonataMediaBundle/blob/master/src/Resources/config/doctrine_orm_admin.php#L31

2021-08-23 07:58 UTC, core23 approved these changes

2021-08-23 08:55 UTC, phansys commented
>>>Could you please provide other PR for the 3.x branch adding a NEXT_MAJOR comment for these removals?
>>
>>Dont know what you mean. Mind to explain?
>
>Adding a "Next major remove this file" message in those files in a 3.x PR I think

That's exactly what I mean. Thank you.

2021-08-23 08:55 UTC, phansys approved these changes

2021-08-24 09:01 UTC, merged