Update documentation
sonata-project/SonataMediaBundle pull request #2181
Opened 2021-10-22 07:07 UTC by jordisala1991

## Subject

I am targeting this branch, because this is the updated docs for 4.0.

Closes #2106

2021-10-22 07:08 UTC, jordisala1991 commented on docs/reference/creating_a_provider_class.rst
> +            'width' => $options['width'] ?? : $media->getWidth(),
wrong ?? :

2021-10-22 07:08 UTC, jordisala1991 commented on docs/reference/helpers.rst
> -PHP Usage
Not sure if that works, but looks like a strange way of using the functions. @sonata-project/contributors

2021-10-23 10:34 UTC, VincentLanglet commented on docs/reference/advanced_configuration.rst
> +        admin_format: { width: 200 , quality: 90, format: 'jpg'}
```suggestion
        admin_format: {width: 200, quality: 90, format: 'jpg'}
```

2021-10-23 10:34 UTC, VincentLanglet commented on docs/reference/advanced_configuration.rst
> +                    big: { width: 500 , quality: 70, resizer: sonata.media.resizer.square}
```suggestion
                    big: {width: 500, quality: 70, resizer: sonata.media.resizer.square}
```

Same for other, the spacing is weird

2021-10-23 10:34 UTC, VincentLanglet commented on docs/reference/media_context.rst
> +                    big: { width: 500 , quality: 70, resizer: sonata.media.resizer.square}
```suggestion
                    big: {width: 500, quality: 70, resizer: sonata.media.resizer.square}
```

same for others

2021-10-24 07:17 UTC, jordisala1991 commented on docs/reference/advanced_configuration.rst
> +        admin_format: { width: 200 , quality: 90, format: 'jpg'}
I decided to add a space between { and the width, I think it reads better that way.

2021-10-24 07:17 UTC, jordisala1991 commented on docs/reference/advanced_configuration.rst
> +                    big: { width: 500 , quality: 70, resizer: sonata.media.resizer.square}
Fixed all spacing

2021-10-24 07:17 UTC, jordisala1991 commented on docs/reference/media_context.rst
> +                    big: { width: 500 , quality: 70, resizer: sonata.media.resizer.square}
Fixed.

2021-10-24 17:00 UTC, VincentLanglet submitted a review, later dismissed

2021-10-26 06:42 UTC, jordisala1991 commented
Please review @sonata-project/contributors

2021-10-26 09:42 UTC, phansys requested changes

2021-10-26 09:42 UTC, phansys commented on docs/index.rst
> +    - ``sonata.media.provider.youtube``: Youtube
```suggestion
    - ``sonata.media.provider.youtube``: [YouTube](https://www.youtube.com/)
```

2021-10-26 09:42 UTC, phansys commented on docs/index.rst
> +    - ``sonata.media.filesystem.replicate``: Replicate file to a master and to a slave
I thought currently we were using "primary" and "secondary", but checking #1778 it seems the change was only partial.

2021-10-26 09:42 UTC, phansys commented on docs/index.rst
> +    - ``sonata.media.cdn.server``: The local http server (default)
```suggestion
    - ``sonata.media.cdn.server``: The local HTTP server (default)
```

2021-10-26 09:42 UTC, phansys commented on docs/index.rst
> +    - ``sonata.media.cdn.cloudfront``: Amazon Cloudfront CDN
```suggestion
    - ``sonata.media.cdn.cloudfront``: [AWS CloudFront](https://aws.amazon.com/cloudfront/)
```

2021-10-26 09:42 UTC, phansys commented on docs/index.rst
> +    - ``sonata.media.provider.vimeo``: Vimeo
```suggestion
    - ``sonata.media.provider.vimeo``: [Vimeo](https://vimeo.com/)
```

2021-10-26 09:42 UTC, phansys commented on docs/index.rst
> +    - ``sonata.media.provider.dailymotion``: Dailymotion
```suggestion
    - ``sonata.media.provider.dailymotion``: [Dailymotion](https://www.dailymotion.com/)
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/advanced_configuration.rst
> +                path: http://xxxxxxxxxxxxxx.cloudfront.net/uploads/media
```suggestion
                path: https://xxxxxxxxxxxxxx.cloudfront.net/uploads/media
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/advanced_configuration.rst
> +                path: http://domain.pantherportal.com/uploads/media
I think this provider does not exist anymore.

2021-10-26 09:42 UTC, phansys commented on docs/reference/creating_a_provider_class.rst
>  is used to generated the media asset public url.
```suggestion
is used to generated the media asset public URL.
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/creating_a_provider_class.rst
> +* video player documentation: http://vimeo.com/api/docs/moogaloop
```suggestion
* video player documentation: https://developer.vimeo.com/player/sdk
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/creating_a_provider_class.rst
> +* metadata: https://vimeo.com/api/oembed.json?url=http://vimeo.com/21216091
```suggestion
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/helpers.rst
> +The default thumbnail must be put in the ``bundles/sonatamedia/file.png``.
```suggestion
The default thumbnail must be put in ``bundles/sonatamedia/file.png``.
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/helpers.rst
> +It is automatically there when you install assets using
```suggestion
It is automatically available there when you install assets using
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/media_context.rst
> +If you look in the ``MediaAdmin`` class, the class defined a ``configurePersistentParameters``
```suggestion
If you look in the ``MediaAdmin`` class, the class defined a ``configurePersistentParameters()``
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/security.rst
> +* ``sonata.media.security.connected_strategy``: the need to have one of the following roles:
```suggestion
* ``sonata.media.security.connected_strategy``: the user needs to have one of the following roles:
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/security.rst
>  On top of that, there is 3 download modes which can be configured to download the media. The download mode depends on
```suggestion
On top of that, there are 3 download modes which can be configured to download the media. The download mode depends on
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/security.rst
> +The Strategy class must implement the ``DownloadStrategyInterface`` which contains 2 main methods:
```suggestion
The strategy class must implement the ``DownloadStrategyInterface`` which contains 2 main methods:
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/security.rst
> +* ``isGranted``: the method test if granted user exists in allowed users for download
```suggestion
* ``isGranted``: the method test if allowed users contains the authenticated user for download
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/usage.rst
> +The providers has a dedicated field where extra information can be saved: the providerMetadata field.
```suggestion
The providers has a dedicated field where extra information can be saved: the ``providerMetadata`` field.
```

2021-10-26 09:42 UTC, phansys commented on docs/reference/security.rst
> +* X-Accel-Redirect: use the ``X-Accel-Redirect`` flag (Nginx: http://wiki.nginx.org/X-accel)
```suggestion
* X-Accel-Redirect: use the ``X-Accel-Redirect`` flag (Nginx: https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/#x-accel-redirect)
```

2021-10-27 06:42 UTC, jordisala1991 commented on docs/index.rst
> +    - ``sonata.media.filesystem.replicate``: Replicate file to a master and to a slave
I will take a look at how is that implemented and if something is missing will open another PR.

2021-10-27 06:45 UTC, jordisala1991 commented on docs/reference/advanced_configuration.rst
> +                path: http://domain.pantherportal.com/uploads/media
Maybe it needs to be removed but it currently exists: https://github.com/sonata-project/SonataMediaBundle/blob/4.x/src/DependencyInjection/Configuration.php#L156-L166

Will take a look. Do you know why it should be removed, or where it was deprecated?

2021-10-27 06:46 UTC, jordisala1991 commented on docs/reference/advanced_configuration.rst
> +                path: http://domain.pantherportal.com/uploads/media
Anyway this will go on another PR because it currently exists

2021-10-27 07:10 UTC, VincentLanglet submitted a review, later dismissed

2021-10-27 09:12 UTC, phansys requested changes

2021-10-27 09:12 UTC, phansys commented on docs/index.rst
> +    - ``sonata.media.cdn.fallback``: Fallback, use the fallback (the http server) if the Media is not yet flushed on the CDN
```suggestion
    - ``sonata.media.cdn.fallback``: Fallback, use the fallback (the HTTP server) if the media is not yet flushed on the CDN
```

2021-10-27 09:12 UTC, phansys commented on docs/reference/advanced_configuration.rst
> +                path: http://domain.pantherportal.com/uploads/media
I'm not referring to our implementation, but the CDN provider itself.
BTW, I agree this must be resolved in a different PR.

2021-10-27 09:12 UTC, phansys commented on docs/reference/creating_a_provider_class.rst
>          $player_parameters =  array_merge($defaults, isset($options['player_parameters']) ? $options['player_parameters'] : []);
```suggestion
        $playerParameters =  array_merge($defaults, isset($options['player_parameters']) ? $options['player_parameters'] : []);
```

2021-10-27 09:12 UTC, phansys commented on docs/reference/creating_a_provider_class.rst
> +            'src' => http_build_query($player_parameters),
```suggestion
            'src' => http_build_query($playerParameters),
```

2021-10-27 09:12 UTC, phansys commented on docs/reference/creating_a_provider_class.rst
> +            'id' => $player_parameters['js_swf_id'],
```suggestion
            'id' => $playerParameters['js_swf_id'],
```

2021-10-27 10:01 UTC, VincentLanglet submitted a review, later dismissed

2021-10-27 10:07 UTC, jordisala1991 commented
After this PR is merged I need to handle:

* Symfony 6 support (waiting for doctrine orm)
* Panther thing, Not sure what to do but something needs to be done
* Replicate thing, search for something to replace

2021-10-27 12:04 UTC, phansys approved these changes

2021-10-27 12:07 UTC, phansys submitted a review, later dismissed

2021-10-27 12:07 UTC, phansys commented on docs/reference/troubleshooting.rst
>                  path: /uploads/media # http://media.sonata-project.org/
```suggestion
                path: /uploads/media
```

2021-10-27 12:07 UTC, phansys commented on docs/reference/advanced_configuration.rst
> +                path: /uploads/media # http://media.sonata-project.org
```suggestion
                path: /uploads/media
```

2021-10-27 12:50 UTC, phansys approved these changes

2021-10-27 12:57 UTC, merged