Make admin dependency optional for blocks
sonata-project/SonataMediaBundle pull request #2219
Opened 2021-11-17 20:17 UTC by core23

#2214 fixed most of the problems, but one block service was missing

## Changelog

```markdown
### Fixed
- Fix block service registration
```

2021-11-17 20:40 UTC, VincentLanglet requested changes

2021-11-17 20:40 UTC, VincentLanglet commented on src/Block/GalleryBlockService.php
> +        ?GalleryManagerInterface $galleryManager
You added the ? on the wrong line

2021-11-17 21:17 UTC, jordisala1991 approved these changes, later dismissed

2021-11-18 14:28 UTC, VincentLanglet requested changes
Phpstan is failing.

2021-11-18 19:16 UTC, jordisala1991 approved these changes

2021-11-18 19:43 UTC, VincentLanglet approved these changes

2021-11-18 19:44 UTC, merged