Use stable version of classification-bundle
sonata-project/SonataMediaBundle pull request #2256
Opened 2022-01-02 12:53 UTC by jordisala1991

## Subject

I am targeting this branch, because this is for next major.

2022-01-02 12:56 UTC, VincentLanglet commented
Psalm failing

2022-01-02 13:41 UTC, jordisala1991 commented
> Psalm failing

Look at this commit: https://github.com/sonata-project/SonataMediaBundle/pull/2256/commits/5a9108d00dc1bb26c32264d93402cc74d05498fc

I don't think this should be needed, but for some reason it is not working without it. It detects scalar instead of string. I can't use assert because phpstan complains.

2022-01-02 14:27 UTC, VincentLanglet commented
I'd like to investigate a little more before adding some psalm-suppress.

The code was ok on the previous PR, we should look which dependency is the reason of this failure

2022-01-02 14:47 UTC, VincentLanglet commented
Ok, I find the issue: it's https://github.com/psalm/psalm-plugin-symfony/issues/233

2022-01-02 16:23 UTC, core23 approved these changes, later dismissed

2022-01-02 19:12 UTC, VincentLanglet requested changes
Can you try again without the psalm-suppress ?

The 3.1.1 version of the psalm plugin is released.

2022-01-02 19:18 UTC, VincentLanglet commented
> Can you try again without the psalm-suppress ?
> 
> The 3.1.1 version of the psalm plugin is released.

I tried locally and I think https://github.com/psalm/psalm-plugin-symfony/pull/235 we'll be needed

2022-01-02 22:31 UTC, VincentLanglet commented on src/Admin/BaseMediaAdmin.php
> +         */
```suggestion
```

2022-01-02 22:31 UTC, VincentLanglet commented on src/Admin/BaseMediaAdmin.php
> +         */
```suggestion
```

2022-01-02 22:31 UTC, VincentLanglet commented on src/Admin/GalleryAdmin.php
> +         */
```suggestion
```

2022-01-02 22:31 UTC, VincentLanglet commented on src/Controller/GalleryAdminController.php
> +             */
```suggestion
```

2022-01-02 22:31 UTC, VincentLanglet commented on src/Controller/MediaAdminController.php
> +             */
```suggestion
```

2022-01-02 22:31 UTC, VincentLanglet commented on src/Controller/MediaAdminController.php
> +         */
```suggestion
```

2022-01-02 22:46 UTC, VincentLanglet approved these changes

2022-01-02 22:46 UTC, merged

2022-01-02 22:46 UTC, VincentLanglet commented
Thanks

2022-01-02 22:47 UTC, VincentLanglet commented
Is it ready for a 4.0.0 release ? @jordisala1991

2022-01-03 03:13 UTC, jordisala1991 commented
> Is it ready for a 4.0.0 release ? @jordisala1991 
> 
> 
> 
> Edit: maybe https://github.com/sonata-project/SonataMediaBundle/issues/2232 need to be solved ?

It would be nice to solve that one indeed. Besides from that, we are ready.

2022-01-14 00:00 UTC, VincentLanglet commented
Did you try the 4.x branch ? @jordisala1991
If it works for you I think we should release the 4.0.0 version even if there is https://github.com/sonata-project/SonataMediaBundle/issues/2232