Fix doctrine mapping
sonata-project/SonataMediaBundle pull request #2420
Opened 2023-11-19 16:07 UTC by core23

## Subject

The recent doctrine dbal update introduced a deprecation warning
```
 [FAIL] The entity-class App\Entity\Media\Media mapping is invalid:

 * The field 'App\Entity\Media\Media#length' has the property type 'float' that differs from the metadata field type 'string' returned by the 'decimal' DBAL type.

 [FAIL] The entity-class Sonata\MediaBundle\Entity\BaseMedia mapping is invalid:

 * The field 'Sonata\MediaBundle\Entity\BaseMedia#length' has the property type 'float' that differs from the metadata field type 'string' returned by the 'decimal' DBAL type.

 [FAIL] The entity-class Core23\MediaBundle\Entity\BaseMedia mapping is invalid:

 * The field 'Core23\MediaBundle\Entity\BaseMedia#length' has the property type 'float' that differs from the metadata field type 'string' returned by the 'decimal' DBAL type.
```

I am targeting this branch, because this is a patch.

## Changelog

```markdown
### Fixed
- Fix doctrine mapping for media length
```

2023-11-19 17:09 UTC, VincentLanglet requested changes

2023-11-19 17:09 UTC, VincentLanglet commented on src/Model/Media.php
> +        $this->length = (string) $length;
```suggestion
        $this->length = null !== $length ? (string) $length : null;
```

2023-11-19 17:09 UTC, VincentLanglet commented on src/Model/Media.php
> +        return (float) $this->length;
```suggestion
        return null !== $this->length ? (float) $this->length : null;
```

2023-11-19 17:09 UTC, VincentLanglet commented on src/Model/Media.php
> +        $this->length = (string) $length;
Maybe this would require a unit test to ensure
```
$media->setLenght(null);
static::assertNull($media->getLength());
```

2023-11-19 18:01 UTC, VincentLanglet approved these changes

2023-11-20 04:09 UTC, dmitryuk commented
Please make a new release after merge

2023-11-20 09:02 UTC, merged

2023-11-21 02:43 UTC, dmitryuk commented
@VincentLanglet can you make a new release?

2023-11-21 13:40 UTC, VincentLanglet commented
> @VincentLanglet can you make a new release?

Done https://github.com/sonata-project/SonataMediaBundle/releases/tag/4.10.5